---
title: "Bootstrap Regression"
author: 'Billy Malherbe'
date: "11/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulated Population Data

```{r}
set.seed(22)

n <- 200000
x <- rnorm(n)
y <- 0.45*x + rnorm(n)
```

## Transform to dataframe 

```{r}
 population_data <- as.data.frame(cbind(x,y))
 sample_data <- population_data[sample(nrow(population_data), 200, replace = TRUE),]
```

## Models of population and sample

```{r}
population_model <- lm(y ~ x, population_data)
summary(population_model)
sample_model <- lm(y~x, data = sample_data)
summary(sample_model)
```
# Plot the models

```{r}
plot(y ~ x, col = rgb(0.7, 0.7, 0.7, 0.5), pch=19, main = 'Population and Sample Regressions')
abline(coef(population_model)[1], coef(population_model)[2], col = "red")
abline(coef(sample_model)[1],
       coef(sample_model)[2],
       col = "blue",
       lty = 2)
legend(
  "topleft",
  legend = c("Sample", "Population"),
  col = c("red", "blue"),
  lty = 1:2,
  cex = 0.8)
```
# The Bootstrap Regression
```{r}
sample_coef_intercept <- NULL
sample_coef_x1 <- NULL

for (i in 1:1000) {
  sample_d = sample_data[sample(1:nrow(sample_data), nrow(sample_data), replace = TRUE), ]
  
  model_bootstrap <- lm(y ~ x, data = sample_d)
  
  sample_coef_intercept <-
    c(sample_coef_intercept, model_bootstrap$coefficients[1])
  
  sample_coef_x1 <-
    c(sample_coef_x1, model_bootstrap$coefficients[2])
}

coefs <- cbind(sample_coef_intercept, sample_coef_x1)



```
# Confidence Interval
```{r}
new.data = seq(min(x), max(x), by = 0.05)
conf_interval <-
  predict(
    sample_model,
    newdata = data.frame(x = new.data),
    interval = "confidence",
    level = 0.95)
```




#Plotting the results on the project step-by-spet
```{r}
plot(
  y ~ x,
  col = "gray",
  xlab = "x",
  ylab = "y",
  main = "Compare regressions")
apply(coefs, 1, abline, col = rgb(1, 0, 0, 0.03))
abline(coef(population_model)[1], coef(population_model)[2], col = "blue")
abline(coef(sample_model)[1],
       coef(sample_model)[2],
       col = "black",
       lty = 2, lwd=3)
abline(mean(sample_coef_intercept),
       mean(sample_coef_x1),
       col = "green",
       lty = 4, lwd=3)
lines(new.data, conf_interval[, 2], col = "black", lty = 3, lwd=3)
lines(new.data, conf_interval[, 3], col = "black", lty = 3, lwd=3)
legend("topleft",
       legend = c("Bootstrap", "Population", 'Sample'),
       col = c("red", "blue", 'green'),
       lty = 1:3,
       cex = 0.8)
```




## The Residual Bootstrap

```{r}
# 1. Run the regression and obtain the estimators and residuals
beta <- sample_model$coefficients[2]
res  <- sample_model$residuals

res_boot <- function(sample_data, res) {
  # 2. Resample the residuals with replacement and obtain the bootstrapped residual vector resb
  resb <- sample(res, length(res), replace = TRUE)
  
  # 3. Obtain the bootstrapped dependent variable by multiplying the estimator(s) from (1) with the original regressors and adding the bootstrapped residual
  yb   <- sample_data$x * beta + resb
  
  # 4. Run the regression with the bootstrapped dependent variables and the original regressors
  regrb <- lm(yb ~ sample_data$x)
  
  unname(regrb$coefficients[2])
}

set.seed(7893454)
beta_boot <- replicate(1000, res_boot(sample_data, res))

```


```{r}
res_coef_intercept <- NULL
res_coef_x1 <- NULL

for (i in 1:1000) {
  sample_residual = sample_data[sample(1:nrow(sample_data), nrow(sample_data), replace = TRUE), ]
  
  model_resi_bootstrap <- lm(y ~ x, data = sample_residual)
  
  res_coef_intercept <-
    c(res_coef_intercept, model_resi_bootstrap$coefficients[1] * population_model$coefficients[1]  )
  
  res_coef_x1 <-
    c(sample_coef_x1, sample_residual)
}

coef_resid <- rbind(res_coef_intercept, res_coef_x1)
```


