---
title: "Double Machine Learning"
author: '109077446'
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(clusterGeneration)
library(mvtnorm)
library(randomForest)
 
set.seed(123) # = Seed for Replication = #
N=500 # = Number of observations = #
k=10 # = Number of variables in z = #
theta=0.5
b=1/(1:k)
 
# = Generate covariance matrix of z = #
sigma=genPositiveDefMat(k,"unifcorrmat")$Sigma
sigma=cov2cor(sigma)

set.seed(123)
M=500 # = Number of Simumations = #
 
# = Matrix to store results = #
thetahat=matrix(NA,M,5)
colnames(thetahat)=c("OLS","Naive DML","Cross-fiting DML", "OLS+z", "DML with sum")


for(i in 1:M){
  z=rmvnorm(N,sigma=sigma) # = Generate z = #
  g=as.vector(cos(z%*%b)^2) # = Generate the function g = #
  m=as.vector(sin(z%*%b)+cos(z%*%b)) # = Generate the function m = #
  d=m+rnorm(N) # = Generate d = #
  y=theta*d+g+rnorm(N) # = Generate y = #
 
  # = OLS estimate = #
  OLS=coef(lm(y~d))[2]
  thetahat[i,1]=OLS
 # = OLS estimate + z= #
  OLS_plus_z=coef(lm(y~d+z))[2]
  thetahat[i,4]=OLS_plus_z
  # = Naive DML = #
  # = Compute ghat = #
  model=randomForest(z,y,maxnodes = 20)
  G=predict(model,z)
  # = Compute mhat = #
  modeld=randomForest(z,d,maxnodes = 20)
  M=predict(modeld,z)
  # = compute vhat as the residuals of the second model = #
  V=d-M
  # = Compute DML theta = #
  theta_nv=mean(V*(y-G))/mean(V*d)
  thetahat[i,2]=theta_nv
 
  # = Cross-fitting DML = #
  # = Split sample = #
  I=sort(sample(1:N,N/2))
  IC=setdiff(1:N,I)
  # = compute ghat on both sample = #
  model1=randomForest(z[IC,],y[IC],maxnodes = 10)
  model2=randomForest(z[I,],y[I], maxnodes = 10)
  G1=predict(model1,z[I,])
  G2=predict(model2,z[IC,])
 
  # = Compute mhat and vhat on both samples = #
  modeld1=randomForest(z[IC,],d[IC],maxnodes = 10)
  modeld2=randomForest(z[I,],d[I],maxnodes = 10)
  M1=predict(modeld1,z[I,])
  M2=predict(modeld2,z[IC,])
  V1=d[I]-M1
  V2=d[IC]-M2
 
  # = Compute Cross-Fitting DML theta
  theta1=mean(V1*(y[I]-G1))/mean(V1*d[I])
  theta2=mean(V2*(y[IC]-G2))/mean(V2*d[IC])
  theta_cf=mean(c(theta1,theta2))
  thetahat[i,3]=theta_cf
 # = Compute Cross-Fitting DML theta with sum
  theta1_sum=sum(V1*(y[I]-G1))/sum(V1*d[I])
  theta2_sum=sum(V2*(y[IC]-G2))/sum(V2*d[IC])
  theta_cf_sum=sum(c(theta1_sum,theta2_sum))
  thetahat[i,5]=theta_cf_sum
}
 
colMeans(thetahat) # = check the average theta for all models = #

```

```{r}
# = plot distributions = #
plot(density(thetahat[,1]),xlim=c(0.3,1.4),ylim=c(0,14))
lines(density(thetahat[,2]),col=2)
lines(density(thetahat[,3]),col=4)
lines(density(thetahat[,4]),lty = 'dashed')
lines(density(thetahat[,5]),col=4, lty = 'dashed')
abline(v=0.5,lty=2,col=3)
legend("topleft",legend=c("OLS","Naive DML","Cross-fiting DML", "OLS+z", "DML with sum"),col=c(1,2,4,1,4),lty=1,cex=0.7,seg.len = 0.7,bty="n")

```

