---
title: "Lasso_"
author: '109077446'
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lasso TUtorial

```{r cars}
library(glmnet)
set.seed(83483473)

#Define predictor and response variables
y <- mtcars$mpg
<<<<<<< HEAD
x <- data.matrix(mtcars[, c('hp', 'wt', 'drat', 'qsec')])
=======
x <- data.matrix(mtcars[, -which(names(mtcars) == ("mpg"))])
>>>>>>> 94162551e4e5e784f88340e71305e4cf6a30ceba

#fit lasso regression model using k-fold cross-validation
cv_model <- cv.glmnet(x, y, alpha = 1)
best_lambda <- cv_model$lambda.min

#display optimal lambda value
best_lambda
```

```{r}
#view coefficients of best model
best_model <- glmnet(x, y, alpha = 1, lambda = best_lambda)
best_coefs <- coef(best_model)
best_coefs
```

```{r}
best_coef_names <- names(which(abs(best_coefs[,"s0"]) > 0.0))
best_coef_names
```

```{r}
#make a prediction for the response value of a new observation
# new = matrix(c(6, 70, ), nrow=1, ncol=3) 
# predict(best_model, s = best_lambda, newx = new)

#find R-squared of model on training data
y_predicted <- predict(best_model, s = best_lambda, newx = x)

sst <- sum((y - mean(y))^2)
sse <- sum((y_predicted - y)^2)

rsq <- 1 - sse/sst
rsq
```

