---
title: "Set_Approach_Validation"
author: '109077446'
date: "1/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
car_setAprproach <- read.table("auto-data.txt", header=FALSE, na.strings = "?")
names(car_setAprproach) <- c("mpg", "cylinders", "displacement", "horsepower", "weight",
"acceleration", "model_year", "origin", "car_name")

new_car_approach <- na.omit(car_setAprproach[,c(1:6)])

summary(new_car_approach)

```


## Center our predictors
```{r}
cylincers.c <- scale(new_car_approach$cylinders, center=TRUE, scale=FALSE)
displacement.c <- scale(new_car_approach$displacement, center=TRUE, scale=FALSE)
horsepower.c <- scale(new_car_approach$horsepower, center=TRUE, scale=FALSE)
weight.c <- scale(new_car_approach$weight, center=TRUE, scale=FALSE)
accelaration.c <- scale(new_car_approach$acceleration, center=TRUE, scale=FALSE)

# add them to the new dataset

new.c.vars <- cbind(cylincers.c, displacement.c, horsepower.c, weight.c, accelaration.c )
new_car_approach <- cbind(new_car_approach, new.c.vars)
names(new_car_approach)[7:11] = c("cylincers.c", "displacement.c", "horsepower.c", "weight.c", "accelaration.c")
summary(new_car_approach)

```
## Create a training and a test dataset with 80% of the data in the training set
```{r}
trainRows <- sample(1:nrow(new_car_approach), 0.8*nrow(new_car_approach))

length(trainRows)
```

## Fit a model in the training data

```{r}

model1 <- lm(mpg ~ cylincers.c + displacement.c + horsepower.c +  weight.c + accelaration.c, data = new_car_approach[c(trainRows), ])
summary(model1)
```
```{r}
# Plot residuals.
par(mfrow=c(2,2))
plot(model1, pch=16)
```
## Predict on the testing dataset and calculate Root Mean Squared Error (RMSE)

```{r}

original <- new_car_approach$mpg
predicted <-  predict(model1, new_car_approach)
ori_pred <- original - predicted

rmse <- sqrt(mean((ori_pred)[-trainRows]^2))
rmse
mae <- mean(abs(ori_pred))
mae
R2 <- 1-(sum((ori_pred)^2) / sum((original - mean(original))^2))
R2


```


